
-- Fix search_path on set_updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

-- Revoke public execute on SECURITY DEFINER functions
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated;

-- ============ SEED SCHOOLS ============
INSERT INTO public.schools (name, type, region, city, tuition_min, tuition_max, accreditation, programs, scholarships_available, pros, cons, fields, source_url, last_verified, valid_until) VALUES
('University of the Philippines Diliman', 'State University', 'NCR', 'Quezon City', 0, 30000, 'PAASCU / AACCUP', ARRAY['Engineering','Business','Education','IT','Sciences','Arts'], true, 'Top-ranked state university; free tuition under UniFAST; strong research', 'Highly competitive UPCAT; limited slots', ARRAY['Engineering / Technology','Business / Accounting / Finance','IT / Programming / Digital','Education / Teaching'], 'https://upd.edu.ph', '2025-01-15', '2027-01-15'),
('Ateneo de Manila University', 'Private University', 'NCR', 'Quezon City', 120000, 180000, 'PAASCU Level IV', ARRAY['Business','Law','Engineering','IT','Communications'], true, 'World-class Jesuit education; strong alumni network', 'High tuition; competitive ACET', ARRAY['Business / Accounting / Finance','Engineering / Technology','IT / Programming / Digital'], 'https://ateneo.edu', '2025-01-15', '2027-01-15'),
('De La Salle University Manila', 'Private University', 'NCR', 'Manila', 110000, 170000, 'PAASCU Level IV', ARRAY['Business','Engineering','IT','Accountancy'], true, 'Strong business and engineering programs; industry links', 'High tuition; strict admission', ARRAY['Business / Accounting / Finance','Engineering / Technology','IT / Programming / Digital'], 'https://dlsu.edu.ph', '2025-01-15', '2027-01-15'),
('University of Santo Tomas', 'Private University', 'NCR', 'Manila', 80000, 130000, 'PAASCU Level IV', ARRAY['Medicine','Nursing','Pharmacy','Engineering','Education'], true, 'Oldest university in Asia; strong health sciences', 'Large student population', ARRAY['Health / Medical / Caregiving','Engineering / Technology','Education / Teaching'], 'https://ust.edu.ph', '2025-01-15', '2027-01-15'),
('Polytechnic University of the Philippines', 'State University', 'NCR', 'Manila', 0, 12000, 'AACCUP', ARRAY['Business','Engineering','IT','Education'], true, 'Very affordable; free tuition under UniFAST', 'Very large classes; competitive PUPCET', ARRAY['Business / Accounting / Finance','Engineering / Technology','IT / Programming / Digital','Education / Teaching'], 'https://pup.edu.ph', '2025-01-15', '2027-01-15'),
('Philippine Science High School System', 'Specialized HS', 'Nationwide', 'Multiple', 0, 0, 'DepEd Specialized', ARRAY['STEM'], true, 'Free STEM-focused senior high; scholarships for college', 'NCE entrance exam is highly competitive', ARRAY['Engineering / Technology','IT / Programming / Digital','Health / Medical / Caregiving'], 'https://pshs.edu.ph', '2025-01-15', '2027-01-15'),
('Mapua University', 'Private University', 'NCR', 'Manila', 100000, 160000, 'ABET-accredited (Engineering)', ARRAY['Engineering','IT','Architecture'], true, 'ABET-accredited engineering; strong IT programs', 'High tuition', ARRAY['Engineering / Technology','IT / Programming / Digital'], 'https://mapua.edu.ph', '2025-01-15', '2027-01-15'),
('MAAP (Maritime Academy of Asia and the Pacific)', 'Maritime Academy', 'Central Luzon', 'Bataan', 0, 0, 'MARINA / CHED', ARRAY['Marine Transportation','Marine Engineering'], true, 'Fully scholarship-based; guaranteed shipboard training', 'Very strict entrance; limited slots (~200/yr)', ARRAY['Maritime / Seafaring'], 'https://maap.edu.ph', '2025-01-15', '2027-01-15'),
('Philippine Merchant Marine Academy', 'State Maritime Academy', 'Central Luzon', 'Zambales', 0, 0, 'MARINA / CHED', ARRAY['Marine Transportation','Marine Engineering'], true, 'Free tuition; government scholarship', 'Military-style discipline; PMMAEE entrance exam', ARRAY['Maritime / Seafaring'], 'https://pmma.edu.ph', '2025-01-15', '2027-01-15'),
('Philippine Military Academy', 'State Military Academy', 'CAR', 'Baguio', 0, 0, 'AFP', ARRAY['Military Science'], true, 'Free education + monthly stipend; guaranteed commission as officer', 'PMAEE + physical/medical requirements; 4-yr service obligation', ARRAY['Military / Public Service'], 'https://pma.edu.ph', '2025-01-15', '2027-01-15'),
('Philippine National Police Academy', 'State Police Academy', 'Cavite', 'Silang', 0, 0, 'PNP', ARRAY['Public Safety'], true, 'Free education + stipend; guaranteed police officer commission', 'PNPACAT entrance exam; physical/medical standards', ARRAY['Military / Public Service'], 'https://pnpa.edu.ph', '2025-01-15', '2027-01-15'),
('Philippine State College of Aeronautics (PhilSCA)', 'State College', 'NCR', 'Pasay', 15000, 30000, 'CHED / CAAP', ARRAY['Aviation','Aircraft Maintenance','Air Transportation'], true, 'Only state aviation college; affordable', 'Flight hours cost extra', ARRAY['Aviation / Pilot / Aircraft'], 'https://philsca.edu.ph', '2025-01-15', '2027-01-15'),
('WCC Aeronautical & Technological College', 'Private College', 'NCR / Central Luzon', 'Multiple', 80000, 250000, 'CAAP-approved', ARRAY['Aviation','Aircraft Maintenance'], false, 'CAAP-certified pilot training', 'Flight hours very expensive (₱1.5M+ total for PPL/CPL)', ARRAY['Aviation / Pilot / Aircraft'], 'https://wcc-aviation.com', '2025-01-15', '2027-01-15'),
('TESDA (nationwide training centers)', 'Government TVET', 'Nationwide', 'Multiple', 0, 5000, 'TESDA Accredited', ARRAY['Welding','Automotive','Cookery','Caregiving','Computer Systems Servicing','Beauty Care','Bookkeeping'], true, 'Free short courses; NC II/III certification; fast to employment', 'Focus is trades, not degree', ARRAY['Skilled Trades / TESDA Courses','Health / Medical / Caregiving','Hospitality / Tourism','IT / Programming / Digital'], 'https://tesda.gov.ph', '2025-01-15', '2027-01-15'),
('Lyceum of the Philippines University', 'Private University', 'NCR', 'Manila', 70000, 110000, 'PAASCU', ARRAY['Hospitality','Tourism','Business','IT'], true, 'Strong hospitality and tourism programs', 'Higher tuition than state schools', ARRAY['Hospitality / Tourism','Business / Accounting / Finance','IT / Programming / Digital'], 'https://lpu.edu.ph', '2025-01-15', '2027-01-15'),
('Enderun Colleges', 'Private College', 'NCR', 'Taguig', 250000, 350000, 'CHED', ARRAY['Hotel Administration','Business'], false, 'Global hospitality reputation; Les Roches partnership', 'Very high tuition', ARRAY['Hospitality / Tourism','Business / Accounting / Finance'], 'https://enderuncolleges.com', '2025-01-15', '2027-01-15'),
('Cebu Institute of Technology - University', 'Private University', 'Central Visayas', 'Cebu City', 60000, 100000, 'PACUCOA', ARRAY['Engineering','IT','Business'], true, 'Top engineering school in Visayas', 'Cebu-based', ARRAY['Engineering / Technology','IT / Programming / Digital'], 'https://cit.edu', '2025-01-15', '2027-01-15'),
('Mindanao State University - IIT', 'State University', 'Northern Mindanao', 'Iligan', 0, 15000, 'AACCUP', ARRAY['Engineering','IT','Sciences'], true, 'Strong engineering in Mindanao; free tuition', 'Location may limit some students', ARRAY['Engineering / Technology','IT / Programming / Digital'], 'https://msuiit.edu.ph', '2025-01-15', '2027-01-15'),
('Xavier University - Ateneo de Cagayan', 'Private University', 'Northern Mindanao', 'Cagayan de Oro', 70000, 110000, 'PAASCU Level IV', ARRAY['Business','Education','Engineering','Agriculture'], true, 'Jesuit university; strong in Mindanao', 'Regional reach', ARRAY['Business / Accounting / Finance','Education / Teaching','Engineering / Technology'], 'https://xu.edu.ph', '2025-01-15', '2027-01-15'),
('Silliman University', 'Private University', 'Central Visayas', 'Dumaguete', 60000, 100000, 'PAASCU Level IV', ARRAY['Nursing','Education','Business','Marine Biology'], true, 'Oldest American-founded uni in Asia; strong nursing', 'Dumaguete-based', ARRAY['Health / Medical / Caregiving','Education / Teaching'], 'https://su.edu.ph', '2025-01-15', '2027-01-15');

-- ============ SEED SCHOLARSHIPS ============
INSERT INTO public.scholarships (name, provider, eligibility, amount, application_window, deadline, fields, regions, source_url, last_verified, valid_until) VALUES
('UniFAST Free Higher Education (Tertiary Education Subsidy)', 'CHED / UniFAST', 'Enrolled in SUC/LUC/eligible private HEIs; Filipino citizen', 'Free tuition + up to ₱40,000/yr stipend', 'Ongoing per SY', NULL, ARRAY['All'], ARRAY['Nationwide'], 'https://unifast.gov.ph', '2025-01-15', '2027-01-15'),
('DOST-SEI Undergraduate Scholarship', 'DOST', 'Incoming college freshmen pursuing STEM; must pass DOST exam', '₱7,000/mo stipend + tuition up to ₱60k/yr + book allowance', 'Aug–Oct', '2025-10-31', ARRAY['Engineering / Technology','IT / Programming / Digital','Health / Medical / Caregiving'], ARRAY['Nationwide'], 'https://sei.dost.gov.ph', '2025-01-15', '2027-01-15'),
('SM Foundation College Scholarship', 'SM Foundation', 'Incoming college freshman; family income ≤ ₱150k/yr; 88%+ average', 'Full tuition + monthly allowance + book allowance', 'Feb–Apr', '2025-04-30', ARRAY['Business / Accounting / Finance','IT / Programming / Digital','Engineering / Technology','Education / Teaching'], ARRAY['Nationwide'], 'https://sm-foundation.org', '2025-01-15', '2027-01-15'),
('Ayala Young Leaders Congress / Scholarships', 'Ayala Foundation', 'Outstanding student leaders in partner schools', 'Varies (leadership program + partial scholarship)', 'Jan–Mar', '2025-03-31', ARRAY['All'], ARRAY['Nationwide'], 'https://ayalafoundation.org', '2025-01-15', '2027-01-15'),
('GSIS Scholarship Program', 'GSIS', 'Dependent of active GSIS member; incoming freshman', '₱40k/yr for 4 years', 'Apr–May', '2025-05-31', ARRAY['All'], ARRAY['Nationwide'], 'https://gsis.gov.ph', '2025-01-15', '2027-01-15'),
('SSS Educational Assistance Loan Program', 'SSS', 'SSS member with dependent in college', 'Up to ₱20,000/yr loan at low interest', 'Ongoing', NULL, ARRAY['All'], ARRAY['Nationwide'], 'https://sss.gov.ph', '2025-01-15', '2027-01-15'),
('Metrobank Foundation Scholarship', 'Metrobank Foundation', 'Incoming freshman; partner university; 88%+ avg', 'Full tuition + allowance', 'Jan–Mar', '2025-03-15', ARRAY['Business / Accounting / Finance','IT / Programming / Digital','Engineering / Technology'], ARRAY['Nationwide'], 'https://mbfoundation.org.ph', '2025-01-15', '2027-01-15'),
('CHED Merit Scholarship (Half/Full)', 'CHED', 'High school top graduates or top scorers in national exam', '₱15k–₱30k/semester', 'May–Jul', '2025-07-31', ARRAY['All'], ARRAY['Nationwide'], 'https://ched.gov.ph', '2025-01-15', '2027-01-15'),
('TESDA Training for Work Scholarship Program (TWSP)', 'TESDA', 'Filipino aged 15+; interested in TVET', 'Free training + toolkit + assessment', 'Ongoing', NULL, ARRAY['Skilled Trades / TESDA Courses','Hospitality / Tourism','IT / Programming / Digital','Health / Medical / Caregiving'], ARRAY['Nationwide'], 'https://tesda.gov.ph', '2025-01-15', '2027-01-15'),
('AFP Educational Benefit System Office (AFPEBSO)', 'AFP', 'Dependent of AFP soldier', 'Tuition assistance for elem–college', 'Ongoing', NULL, ARRAY['All'], ARRAY['Nationwide'], 'https://afp.mil.ph', '2025-01-15', '2027-01-15'),
('Philippine Air Force Cadet (PAFFS)', 'PAF', 'Aged 18-22, PMA/OCS candidate; medical/physical pass', 'Free training + salary as commissioned officer', 'Feb–May', '2025-05-31', ARRAY['Military / Public Service','Aviation / Pilot / Aircraft'], ARRAY['Nationwide'], 'https://paf.mil.ph', '2025-01-15', '2027-01-15'),
('MARINA Cadet Scholarship (via MAAP/PMMA)', 'MARINA', 'Passed academy entrance; medical/physical pass', 'Full academy scholarship + allowance', 'Sep–Dec', '2025-12-15', ARRAY['Maritime / Seafaring'], ARRAY['Nationwide'], 'https://marina.gov.ph', '2025-01-15', '2027-01-15'),
('Jollibee Group Foundation Scholarship', 'Jollibee Group Foundation', 'Incoming freshman; family income ≤ ₱150k/yr; academic excellence', 'Full tuition + allowance', 'Feb–Apr', '2025-04-30', ARRAY['Business / Accounting / Finance','Hospitality / Tourism'], ARRAY['Nationwide'], 'https://jollibeegroupfoundation.org', '2025-01-15', '2027-01-15'),
('DepEd Senior High School Voucher', 'DepEd', 'JHS Grade 10 completer entering SHS in private/non-DepEd school', '₱9,000–₱22,500/yr for SHS', 'Mar–Jun', '2025-06-30', ARRAY['All'], ARRAY['Nationwide'], 'https://deped.gov.ph', '2025-01-15', '2027-01-15'),
('CHED-Study Grant Program for Solo Parents/PWDs', 'CHED', 'Solo parent or dependent, or PWD', '₱30k–₱60k/yr', 'Ongoing', NULL, ARRAY['All'], ARRAY['Nationwide'], 'https://ched.gov.ph', '2025-01-15', '2027-01-15');

-- ============ SEED CAREERS ============
INSERT INTO public.careers (name, field, description, requirements, typical_path, starting_salary_min, starting_salary_max, mid_salary_min, mid_salary_max, source_url, last_verified) VALUES
('Certified Public Accountant', 'Business / Accounting / Finance', 'Prepares and audits financial records for companies and individuals.', 'BS Accountancy + pass CPA Board (PRC)', '4-yr BSA → CPA review → CPA board → junior accountant → senior/manager', 25000, 35000, 60000, 120000, 'https://prc.gov.ph', '2025-01-15'),
('Financial Analyst', 'Business / Accounting / Finance', 'Analyzes financial data to guide investment and business decisions.', 'BS Finance/Accountancy/Economics', 'BS → analyst → senior analyst → finance manager', 22000, 35000, 55000, 110000, 'https://dole.gov.ph', '2025-01-15'),
('Software Engineer', 'IT / Programming / Digital', 'Designs and builds software applications and systems.', 'BS Computer Science / IT / Software Eng.', 'BS → junior dev → mid → senior → tech lead', 30000, 55000, 80000, 200000, 'https://dole.gov.ph', '2025-01-15'),
('Data Analyst', 'IT / Programming / Digital', 'Turns raw data into actionable business insights.', 'BS in IT/CS/Stats/Math; SQL & Python', 'BS → analyst → senior analyst → data scientist', 28000, 45000, 60000, 120000, 'https://dole.gov.ph', '2025-01-15'),
('Registered Nurse', 'Health / Medical / Caregiving', 'Provides patient care in hospitals and clinics.', 'BS Nursing + PRC Nursing Board License', 'BSN → NLE → hospital staff → specialist/abroad', 18000, 28000, 40000, 80000, 'https://prc.gov.ph', '2025-01-15'),
('Caregiver (NC II)', 'Health / Medical / Caregiving', 'Provides personal care and assistance, often for elderly or children.', 'TESDA Caregiving NC II (~6 months)', 'TESDA NC II → local/agency → overseas (Japan/Canada)', 12000, 20000, 25000, 60000, 'https://tesda.gov.ph', '2025-01-15'),
('Civil Engineer', 'Engineering / Technology', 'Designs and supervises construction of infrastructure.', 'BS Civil Engineering + PRC Board', 'BSCE → PRC Board → junior engineer → project engineer → PM', 25000, 40000, 60000, 130000, 'https://prc.gov.ph', '2025-01-15'),
('Mechanical Engineer', 'Engineering / Technology', 'Designs machines, HVAC, and manufacturing systems.', 'BS Mechanical Engineering + PRC Board', 'BSME → PRC → plant engineer → senior/consultant', 25000, 40000, 60000, 130000, 'https://prc.gov.ph', '2025-01-15'),
('Electrical Engineer', 'Engineering / Technology', 'Designs electrical systems for buildings, power, and electronics.', 'BS Electrical Engineering + PRC Board', 'BSEE → PRC → junior → registered/professional', 25000, 40000, 60000, 130000, 'https://prc.gov.ph', '2025-01-15'),
('Elementary / High School Teacher', 'Education / Teaching', 'Teaches children and youth in public or private schools.', 'BEEd/BSEd + LET (PRC)', 'BEEd/BSEd → LET → Teacher I → Master Teacher/Principal', 27000, 32000, 45000, 70000, 'https://deped.gov.ph', '2025-01-15'),
('Airline Pilot (Commercial)', 'Aviation / Pilot / Aircraft', 'Flies commercial aircraft for airlines.', 'CAAP CPL + ATPL, medical, ~250 flight hrs to start', 'PPL → CPL (₱1.5M–₱3M training) → 250 hrs → cadet program (PAL/Cebu Pacific) → First Officer → Captain', 80000, 150000, 250000, 500000, 'https://caap.gov.ph', '2025-01-15'),
('Aircraft Maintenance Technician', 'Aviation / Pilot / Aircraft', 'Inspects and repairs aircraft components.', 'CAAP AMT License + BS Aeronautical Eng. or 2-yr AMT program', '2-yr program → CAAP exam → junior tech → licensed A&P', 22000, 40000, 55000, 100000, 'https://caap.gov.ph', '2025-01-15'),
('Deck Officer (Merchant Marine)', 'Maritime / Seafaring', 'Navigates and manages operations aboard commercial vessels.', 'BS Marine Transportation + MARINA license + shipboard training', 'BSMT → apprentice → 3rd Officer → 2nd → Chief Mate → Captain', 60000, 120000, 200000, 500000, 'https://marina.gov.ph', '2025-01-15'),
('Marine Engineer', 'Maritime / Seafaring', 'Operates and maintains ship engines and mechanical systems.', 'BS Marine Engineering + MARINA license', 'BSMarE → apprentice → 4th → 3rd → 2nd → Chief Engineer', 60000, 120000, 200000, 500000, 'https://marina.gov.ph', '2025-01-15'),
('Hotel & Restaurant Manager', 'Hospitality / Tourism', 'Manages hotel or restaurant operations and staff.', 'BS Hotel & Restaurant Management or Tourism', 'BS → supervisor → manager → GM', 20000, 35000, 50000, 120000, 'https://dole.gov.ph', '2025-01-15'),
('Chef / Culinary Professional', 'Hospitality / Tourism', 'Prepares food in restaurants, hotels, or catering.', 'TESDA Cookery NC II/III or Culinary degree', 'TESDA/Culinary → line cook → sous chef → head chef', 15000, 30000, 45000, 100000, 'https://tesda.gov.ph', '2025-01-15'),
('Welder (SMAW/GTAW)', 'Skilled Trades / TESDA Courses', 'Joins metal parts for construction, shipyards, manufacturing.', 'TESDA SMAW/GTAW NC II–III', 'TESDA NC II → local → NC III → overseas (Middle East)', 15000, 30000, 40000, 90000, 'https://tesda.gov.ph', '2025-01-15'),
('Automotive Servicing Technician', 'Skilled Trades / TESDA Courses', 'Repairs and maintains motor vehicles.', 'TESDA Automotive Servicing NC I–III', 'TESDA → shop apprentice → licensed tech → shop owner', 14000, 25000, 35000, 70000, 'https://tesda.gov.ph', '2025-01-15'),
('Police Officer (Patrolman)', 'Military / Public Service', 'Enforces laws and protects communities.', 'BS Criminology or PNPA + NAPOLCOM exam', 'BS Crim → NAPOLCOM → PNP training → PO1 → officer ranks', 30000, 40000, 55000, 90000, 'https://pnp.gov.ph', '2025-01-15'),
('Enlisted Soldier (Philippine Army/Navy/Air Force)', 'Military / Public Service', 'Serves the country as an enlisted member of the AFP.', 'Filipino, 18-26, HS grad, physical/medical pass', 'Basic training → Private → NCO promotions', 30000, 40000, 50000, 80000, 'https://afp.mil.ph', '2025-01-15'),
('Digital Marketing Specialist', 'IT / Programming / Digital', 'Runs online ads, SEO, and social media for brands.', 'BS Marketing/Comm + digital certifications', 'Junior → specialist → manager → head of growth', 20000, 35000, 45000, 90000, 'https://dole.gov.ph', '2025-01-15'),
('Web / Graphic Designer', 'IT / Programming / Digital', 'Designs websites, apps, and visual content.', 'BS Multimedia Arts / short courses + portfolio', 'Junior → mid → senior → art director / freelance', 18000, 32000, 45000, 90000, 'https://dole.gov.ph', '2025-01-15'),
('Bookkeeper (NC III)', 'Business / Accounting / Finance', 'Records daily financial transactions for small businesses.', 'TESDA Bookkeeping NC III (~3–6 months)', 'TESDA → SME bookkeeper → senior', 15000, 22000, 25000, 45000, 'https://tesda.gov.ph', '2025-01-15'),
('Beauty Care / Wellness Professional', 'Skilled Trades / TESDA Courses', 'Provides beauty, hair, and wellness services.', 'TESDA Beauty Care NC II or Wellness Massage NC II', 'TESDA → salon/spa → own business or overseas', 12000, 22000, 25000, 60000, 'https://tesda.gov.ph', '2025-01-15'),
('Coast Guard Officer', 'Military / Public Service', 'Enforces maritime law and search-and-rescue operations.', 'BS Marine/Naval or Coast Guard Officer Course', 'BS + CGOAC training → Ensign → officer ranks', 32000, 45000, 55000, 90000, 'https://coastguard.gov.ph', '2025-01-15');
